services:
  redis:
    image: redis:latest
    container_name: redis_pokeapi
    ports:
      - "6379:6379" # Redis server port
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  web:
    build: .
    container_name: fastpoke-api
    ports:
    - "8000:8000"
    depends_on:
    - redis
    environment:
    - REDIS_URL=redis://redis:6379
    volumes:
    - .:/app
