[project]
name = "fastpoke-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.121.0",
    "httpx>=0.28.1",
    "redis>=7.0.1",
]
